name: Agendalor

# オプション設定
options:
  # バンドルプレフィックス
  bundleIdPrefix: Agendalor
  # LocalizationsのDevelopment Languageを指定
  developmentLanguage: ja

# Swift Package Managerのパッケージ設定
packages:
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    from: 4.4.3

# ターゲットごとの設定
targets:
  Agendalor:
    # ターゲットの製品タイプ
    type: application
    # ターゲットのプラットフォーム
    platform: iOS
    # デプロイメントターゲット
    deploymentTarget: "18.0.0"

    # 採用するFirebaseのサービス
    dependencies:
      - package: Lottie
        product: Lottie

    # ソースコードとその他のファイル
    sources:
      - Agendalor
      - project.yml
      - .gitignore
    resources:
      - Resources

    # ビルド設定
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: algoria.Agendalor
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: algoria
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -all_load

    # Info.plist設定
    info:
      path: Agendalor/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Light

  AgendalorTests:
    type: bundle.unit-test
    platform: iOS
    sources: [AgendalorTests]
    dependencies:
      - target: Agendalor




